name: CI Check

on:
  push:
    branches: [ "**" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: |
            11
            21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check
        run: ./gradlew test